import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { NEXT_AUTH_CONFIG } from "@/lib/auth";
import { getServerSession } from "next-auth";
import { Toaster } from 'react-hot-toast';
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "VenULY",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(NEXT_AUTH_CONFIG);
  const isAdmin = session?.user?.email === process.env.ADMIN_EMAIL;
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Navbar session={session} isAdmin={isAdmin}/>
          <Toaster position="bottom-left" reverseOrder={false} />
        {children}
        </Providers>
      </body>
    </html>
  );
}
